### ISSUE TITLE
add contrast comparisons between peaks

### ISSUE THREAD

**Issue by slsevilla** [CCBR/ASPEN#15]
- [ ] updating config to take in contrast.tsv
- [ ] create rules to run deeptools on samples (correlation matrix, heatmaps, profiles, summary)
- [ ] create rules to create counts matrix
- [ ] create rules to perform DESEQ between contrasts - output a diffresults.txt
- [ ] create rules to perform conversion of diffresults to bed file

**Comment by slsevilla** [comment]
ASAP dir already run:

[12:46 PM] Goldfarbmuren, Kate (NIH/NCI) [C]
/data/NCI_VB/berzofsky/ccrvb16_2018invitroHuman_ATACseq_KCG/ASAP_221212/

[12:47 PM] Goldfarbmuren, Kate (NIH/NCI) [C]
/data/NCI_VB/berzofsky/ccrvb16_2018invitroHuman_ATACseq_KCG/PostASAP_dev/

**Comment by kopardev** [comment]
I already have scripts for most of these. Let's talk next week. I don't want you to reinvent the wheel.

**Comment by slsevilla** [comment]
Plan counts matrix
- take output from atac_genrich_peakcalling_fixed_width : 
    - renormalizedConsensusNarrowPeak=join(RESULTSDIR,"peaks","genrich","fixed_width","{sample}.renormalized.fixed_width.consensus.narrowPeak")
- run python [script](https://github.com/CCBR/CARLISLE/blob/master/workflow/scripts/_make_counts_matrix.py)
   - python {params.pyscript} --bedbedgraph {input.inputs} --tmpdir $TMPDIR --countsmatrix {output.cm} --fragmentscountsmatrix {output.fcm} --sampleinfo {output.si}

plan differential: 
- create config file with contrasts
- perform QC check - contrasts are in sample manifest
- run [DESEQ](https://github.com/CCBR/CARLISLE/blob/master/workflow/scripts/_diff_markdown.Rmd) on contrasts

**Comment by slsevilla** [comment]
Counts matrix: https://github.com/CCBR/ASAP/issues/17

**Comment by slsevilla** [comment]
http://genomespot.blogspot.com/2015/01/generate-rna-seq-count-matrix-with.html
