### ISSUE TITLE
add Counts Matrix to workflow

### ISSUE THREAD

**Issue by slsevilla** [CCBR/ASPEN#17]
Ask: add countsmatrix to the workflow

Plan: 
- take output from atac_genrich_peakcalling_fixed_width :
renormalizedConsensusNarrowPeak=join(RESULTSDIR,"peaks","genrich","fixed_width","{sample}.renormalized.fixed_width.consensus.narrowPeak")
- run python [script](https://github.com/CCBR/CARLISLE/blob/master/workflow/scripts/_make_counts_matrix.py)
python {params.pyscript} --bedbedgraph {input.inputs} --tmpdir $TMPDIR --countsmatrix {output.cm} --fragmentscountsmatrix {output.fcm} --sampleinfo {output.si}

**Comment by slsevilla** [comment]
@kopardev - I was updating CARLISLE's count matrix and came here to check out adding this rule; now have a question. 

I was planning on using the _fixed_width input as the bed file for this but now I'm not sure we want to do that give it's a normalized bed file. Instead, I'm thinking we should be using the pre-fixed-width file, although I'm not sure how this is going to work with varied widths. 

I attempted a run with the fixed_withs with two samples, and while the script did compile all the peaks, everything is set to 500:

peakID | DG9X_CD3_Basal_ALVAC | DG9X_CD3_Wk7_ALVAC |
| -- | -- | -- |
chr14:13966466-13967421 | 500.0 | 500.0
chr20:29809460-29810265 | 500.0 | 500.0
chr14:13803936-13804443 | 500.0 | 500.0
chr14:13910207-13910708 | 500.0 | 500.0

Let me know what you think!

**Comment by kopardev** [comment]
@slsevilla let us discuss this tomorrow.

**Comment by slsevilla** [comment]
@kopardev to send counts matrix updated code specific for ATAC data. Will add to pipeline when received.
